name: Validate Pull Requests to Main
on: 
  pull_request:
    branches: [main]

jobs:
  validate-pull-requests-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          echo "Validate pull request:"
          echo "${{ github.event.pull_request.head.sha }}"
          git fetch --all
          git checkout develop
          git merge --no-commit --no-ff "${{ github.event.pull_request.head.sha }}"
          echo "Status code of git merge $?"